// <auto-generated />
using AnimalsApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalsApi.Migrations
{
    [DbContext(typeof(AnimalsContext))]
    partial class AnimalsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalsApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("About")
                        .HasColumnType("longtext");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            About = "lovable little dog found eating a taco in downtown, needs a home",
                            Age = 3,
                            Name = "Spot",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            About = "this big orange chonk loves to eat and and cuddle needs a home",
                            Age = 6,
                            Name = "Muffin",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            About = " please help us ",
                            Age = 769736544,
                            Name = "Mogar the Destroyer",
                            Species = "Inner Dimensional Soul Eater"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
